# Data volume

NUM_DEPARTMENTS = 55
NUM_PATIENTS = 100_000
NUM_MEDICINES = 1_000
NUM_DOCTORS = 500
NUM_ROOMS = 250
NUM_APPOINTMENTS = 500_000


# Date range

DATA_START_DATE = "2020-01-01"
FUTURE_APPOINTMENT_MONTHS = 3

# Appointment status rules

COMPLETED_RATE = 0.80
CANCELLED_RATE = 0.10
NO_SHOW_RATE = 0.10

# Medical record rules

MEDICAL_RECORD_RATE = 0.9375

# Prescription rules

PRESCRIPTION_RATE = 0.70
MIN_PRESCRIPTIONS_PER_RECORD = 1
MAX_PRESCRIPTIONS_PER_RECORD = 2

# Prescription item rules

MIN_MEDICINES_PER_PRESCRIPTION = 1
MAX_MEDICINES_PER_PRESCRIPTION = 5

# Invoice rules

INVOICE_PER_RECORD = 1

# Payment rules

PAYMENT_RATE = 0.85